#!/bin/env bash
# bash script to transfer file to a remote server

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

filepath=$1
ip=$2
usrname=$3
sshpath=$4

# Transfer the file to the server
scp -i "$sshpath" -o StrictHostKeyChecking=no "$filepath" "$usrname@$ip:~/"
