#!/usr/bin/env bash
# script to configure nginx so that its HTTP response contains a custom header (on web-01 and web-02)

#update and installation of nginx
sudo apt-get update
sudo apt-get install nginx -y

#appeding Heelo world in the index file
sudo tee /var/www/html/index.html <<< "Hello World!"

# adding redirection
sudo sed -i '/server_name _;/a \        location /redirect_me {\n                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default

# appending Ceci n'est pas une page when page is a 404
sudo tee /var/www/html/custom_404.html <<< "Ceci n'est pas une page"

#adds a custom 404 error page and a custom HTTP header to the header
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }\n\n        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# restarting nginx
sudo service nginx restart
