#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
trap 'echo "I am invincible!!!"' SIGTERM
var=0
while [ "$var" ];
do
    echo To infinity and beyond
    sleep 2;
done
