#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
count=10
for i in $(seq $count); do
    echo Best School
done

#for run in {1..10}; do
#    echo Best School
#done
#for run in {1..10}; do echo Best School; done
