#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

var=1
while ((var <= 20));
do
    case $var in
        4)
            echo $var
            echo bad luck from China
            ;;
        9)
            echo $var
            echo bad luck from Japan
            ;;
        17)
            echo $var
            echo bad luck from Italy
	    ;;
        *)
            echo $var
            ;;
    esac
    ((var++))
    done
