#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
hr=0
while ((hr <= 12));
do
    min=1
    echo "Hour: " "$hr"
    while ((min <= 59));
    do
        echo "$min";
        ((min++))
    done
    ((hr++));
done
