#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
hr=0
while [ "$hr" -ne 13 ];
do
    min=1
    echo "Hour: $hr"
    while [ "$min" -ne 60 ];
    do
        echo "$min"
        ((min++))
    done
    ((hr++))
done
