#!/usr/bin/env bash
#Bash script that gives you information about the school file.
for entry in school
do
    if [ -a $entry ]; then
        echo school file exists
        if [ ! -s $entry ]; then
            echo school file is empty
        elif [ -s $entry ]; then
            echo school file is not empty
        fi
        if [ -f $entry ]; then
            echo school is a regular file
        elif [ ! -f $entry ]; then
            continue
        fi
    else
        echo school file does not exists
    fi
done
